apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: helloworld.nginx.com
  labels:
    app: helloworld-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - name: nginx-port
      containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: nodejs
    image: mailfigo/hello-world-njs-rp:1
    ports:
    - name: nodejs-port
      containerPort: 8080
  volumes:
   - name: config-volume
     configMap:
      name: nginx-config
      items:
      - key: reverseproxy.conf
        path: reverseproxy.conf
