apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: nodejs-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: 80
    protocol: TCP
  selector:
    app: nodejs
  type: NodePort
