apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: helloworld-v1
  labels:
    app: helloworld-v1
spec:
  containers:
  - name: nodejs
    image: mailfigo/hello-world-njs:1
    ports:
    - name: nodejs-port
      containerPort: 80
    volumeMounts:
    - name: autoprov
      mountPath: /mnt
  volumes:
   - name: autoprov
     persistentVolumeClaim: 
      claimName: helloworld-v1-pvc 
