apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: helloworld-fimg
  labels:
    app: nodejs-fimg
spec:
  containers:
  - name: nodejs-fimg
    image: mailfigo/hello-world-njs:1
    ports:
    - name: nodejsfimg-port
      containerPort: 80
